/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.tarororo.brew.defs'

export { $nsid }

/** Launch via a web URL. */
type LaunchWeb = {
  $type?: 'org.tarororo.brew.defs#launchWeb'

  /**
   * Web URL to open.
   */
  link: l.UriString
}

export type { LaunchWeb }

/** Launch via a web URL. */
const launchWeb = l.typedObject<LaunchWeb>(
  $nsid,
  'launchWeb',
  l.object({ link: l.string({ format: 'uri' }) }),
)

export { launchWeb }

/** Launch brew store. */
type LaunchStore = { $type?: 'org.tarororo.brew.defs#launchStore' }

export type { LaunchStore }

/** Launch brew store. */
const launchStore = l.typedObject<LaunchStore>(
  $nsid,
  'launchStore',
  l.object({}),
)

export { launchStore }

/** hydrated view for a store item. */
type StoreItemView = {
  $type?: 'org.tarororo.brew.defs#storeItemView'

  /**
   * Display title.
   */
  title: string

  /**
   * Short summary for display.
   */
  description?: string

  /**
   * Display name of the author.
   */
  author?: string

  /**
   * Launch target for this item.
   */
  launch: l.$Typed<LaunchWeb> | l.$Typed<LaunchStore> | l.Unknown$TypedObject

  /**
   * Public URL of a thumbnail image.
   */
  thumbnail: l.UriString

  /**
   * AT URI of the storeItem record.
   */
  uri: l.AtUriString

  /**
   * Raw storeItem record value.
   */
  record: l.LexMap
}

export type { StoreItemView }

/** hydrated view for a store item. */
const storeItemView = l.typedObject<StoreItemView>(
  $nsid,
  'storeItemView',
  l.object({
    title: l.string(),
    description: l.optional(l.string()),
    author: l.optional(l.string()),
    launch: l.typedUnion(
      [
        l.typedRef<LaunchWeb>((() => launchWeb) as any),
        l.typedRef<LaunchStore>((() => launchStore) as any),
      ],
      false,
    ),
    thumbnail: l.string({ format: 'uri' }),
    uri: l.string({ format: 'at-uri' }),
    record: l.lexMap(),
  }),
)

export { storeItemView }
