/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as BrewDefs from './defs.defs.js'

const $nsid = 'org.tarororo.brew.getLauncher'

export { $nsid }

/** Fetch the launcher view. Auth: required. */
const main = l.query(
  $nsid,
  l.params(),
  l.jsonPayload({
    items: l.ref<LauncherItems>((() => launcherItems) as any),
    record: l.lexMap(),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

/** Array of store item views. */
type LauncherItems = BrewDefs.StoreItemView[]

export type { LauncherItems }

/** Array of store item views. */
const launcherItems = l.array<LauncherItems[number]>(
  l.ref<BrewDefs.StoreItemView>((() => BrewDefs.storeItemView) as any),
)

export { launcherItems }
