/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as BrewStoreItem from './storeItem.defs.js'

const $nsid = 'org.tarororo.brew.getLauncher'

export { $nsid }

const main = l.query(
  $nsid,
  l.params(),
  l.jsonPayload({
    view: l.ref<LauncherView>((() => launcherView) as any),
    record: l.lexMap(),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type LauncherView = LauncherViewItem[]

export type { LauncherView }

const launcherView = l.array<LauncherView[number]>(
  l.ref<LauncherViewItem>((() => launcherViewItem) as any),
)

export { launcherView }

type LauncherViewItem = {
  $type?: 'org.tarororo.brew.getLauncher#launcherViewItem'
  title: string
  description: string
  author: string
  launch:
    | l.$Typed<BrewStoreItem.LaunchWeb>
    | l.$Typed<BrewStoreItem.LaunchStore>
    | l.Unknown$TypedObject
  thumbnail: l.UriString
  uri: l.AtUriString
  record: l.LexMap
}

export type { LauncherViewItem }

const launcherViewItem = l.typedObject<LauncherViewItem>(
  $nsid,
  'launcherViewItem',
  l.object({
    title: l.string(),
    description: l.string(),
    author: l.string(),
    launch: l.typedUnion(
      [
        l.typedRef<BrewStoreItem.LaunchWeb>(
          (() => BrewStoreItem.launchWeb) as any,
        ),
        l.typedRef<BrewStoreItem.LaunchStore>(
          (() => BrewStoreItem.launchStore) as any,
        ),
      ],
      false,
    ),
    thumbnail: l.string({ format: 'uri' }),
    uri: l.string({ format: 'at-uri' }),
    record: l.lexMap(),
  }),
)

export { launcherViewItem }
