/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.tarororo.brew.getLauncher'

export { $nsid }

const main = l.query(
  $nsid,
  l.params(),
  l.jsonPayload({
    view: l.ref<LauncherView>((() => launcherView) as any),
    record: l.lexMap(),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type LauncherView = LauncherViewItem[]

export type { LauncherView }

const launcherView = l.array<LauncherView[number]>(
  l.ref<LauncherViewItem>((() => launcherViewItem) as any),
)

export { launcherView }

type LauncherViewItem = {
  $type?: 'org.tarororo.brew.getLauncher#launcherViewItem'
  title?: string
  description?: string
  author?: string

  /**
   * TODO
   */
  launch?: l.LexMap
  thumbnail: l.UriString
  record: l.LexMap
}

export type { LauncherViewItem }

const launcherViewItem = l.typedObject<LauncherViewItem>(
  $nsid,
  'launcherViewItem',
  l.object({
    title: l.optional(l.string()),
    description: l.optional(l.string()),
    author: l.optional(l.string()),
    launch: l.optional(l.lexMap()),
    thumbnail: l.string({ format: 'uri' }),
    record: l.lexMap(),
  }),
)

export { launcherViewItem }
