/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as BrewDefs from './defs.defs.js'

const $nsid = 'org.tarororo.brew.getStoreItem'

export { $nsid }

/** Fetch a store item view by record URI. Auth: none. */
const main = l.query(
  $nsid,
  l.params({ uri: l.string({ format: 'at-uri' }) }),
  l.payload(
    'application/json',
    l.ref<BrewDefs.StoreItemView>((() => BrewDefs.storeItemView) as any),
  ),
  ['NotFoundError'],
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
