/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'org.tarororo.brew.launcher'

export { $nsid }

type Main = { $type: 'org.tarororo.brew.launcher'; items: Item[] }

export type { Main }

const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({ items: l.array(l.ref<Item>((() => item) as any)) }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Item = {
  $type?: 'org.tarororo.brew.launcher#item'
  storeItemRef?: RepoStrongRef.Main
}

export type { Item }

const item = l.typedObject<Item>(
  $nsid,
  'item',
  l.object({
    storeItemRef: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
  }),
)

export { item }
