/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'org.tarororo.brew.launcher'

export { $nsid }

/** Launcher record for an account. */
type Main = {
  $type: 'org.tarororo.brew.launcher'

  /**
   * Ordered list of store items to show.
   */
  items: Item[]

  /**
   * Creation timestamp.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Launcher record for an account. */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    items: l.array(l.ref<Item>((() => item) as any), { maxLength: 100 }),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Entry in the launcher list. */
type Item = {
  $type?: 'org.tarororo.brew.launcher#item'

  /**
   * Reference to a storeItem record.
   */
  storeItemRef?: RepoStrongRef.Main
}

export type { Item }

/** Entry in the launcher list. */
const item = l.typedObject<Item>(
  $nsid,
  'item',
  l.object({
    storeItemRef: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
  }),
)

export { item }
