/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as BrewDefs from './defs.defs.js'

const $nsid = 'org.tarororo.brew.storeItem'

export { $nsid }

/** Store item record. */
type Main = {
  $type: 'org.tarororo.brew.storeItem'

  /**
   * Display title.
   */
  title: string

  /**
   * Short summary for display.
   */
  description?: string

  /**
   * Display name of the author.
   */
  author?: string

  /**
   * Launch target for this item.
   */
  launch:
    | l.$Typed<BrewDefs.LaunchWeb>
    | l.$Typed<BrewDefs.LaunchStore>
    | l.Unknown$TypedObject

  /**
   * Thumbnail image. Accepts image/* up to 2000000 bytes.
   */
  thumbnail: l.BlobRef

  /**
   * Creation timestamp.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Store item record. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    title: l.string({ maxGraphemes: 50 }),
    description: l.optional(l.string({ maxGraphemes: 1000 })),
    author: l.optional(l.string({ maxGraphemes: 50 })),
    launch: l.typedUnion(
      [
        l.typedRef<BrewDefs.LaunchWeb>((() => BrewDefs.launchWeb) as any),
        l.typedRef<BrewDefs.LaunchStore>((() => BrewDefs.launchStore) as any),
      ],
      false,
    ),
    thumbnail: l.blob({ accept: ['image/*'], maxSize: 2000000 }),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
