/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.tarororo.brew.storeItem'

export { $nsid }

type Main = {
  $type: 'org.tarororo.brew.storeItem'
  title: string
  description: string
  author: string
  launch: l.$Typed<LaunchWeb> | l.Unknown$TypedObject
  thumbnail: l.BlobRef
}

export type { Main }

const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    title: l.string(),
    description: l.string(),
    author: l.string(),
    launch: l.typedUnion(
      [l.typedRef<LaunchWeb>((() => launchWeb) as any)],
      false,
    ),
    thumbnail: l.blob(),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type LaunchWeb = {
  $type?: 'org.tarororo.brew.storeItem#launchWeb'
  link: l.UriString
}

export type { LaunchWeb }

const launchWeb = l.typedObject<LaunchWeb>(
  $nsid,
  'launchWeb',
  l.object({ link: l.string({ format: 'uri' }) }),
)

export { launchWeb }
