/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

export * as defs from './repo/defs.js'
export * as getRecord from './repo/getRecord.js'
export * as putRecord from './repo/putRecord.js'
export * as strongRef from './repo/strongRef.js'
