/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ActorDefs from '../actor/defs.defs.js'
import * as LabelDefs from '../../../com/atproto/label/defs.defs.js'

const $nsid = 'app.bsky.notification.listNotifications'

export { $nsid }

/** Enumerate notifications for the requesting account. Requires auth. */
const main = l.query(
  $nsid,
  l.params({
    limit: l.optional(
      l.withDefault(l.integer({ maximum: 100, minimum: 1 }), 50),
    ),
    cursor: l.optional(l.string()),
    seenAt: l.optional(l.string({ format: 'datetime' })),
    reasons: l.optional(l.array(l.string())),
    priority: l.optional(l.boolean()),
  }),
  l.jsonPayload({
    cursor: l.optional(l.string()),
    seenAt: l.optional(l.string({ format: 'datetime' })),
    priority: l.optional(l.boolean()),
    notifications: l.array(l.ref<Notification>((() => notification) as any)),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type Notification = {
  $type?: 'app.bsky.notification.listNotifications#notification'
  cid: l.CidString
  uri: l.AtUriString
  author: ActorDefs.ProfileView
  isRead: boolean
  labels?: LabelDefs.Label[]

  /**
   * The reason why this notification was delivered - e.g. your post was liked, or you received a new follower.
   */
  reason:
    | 'like'
    | 'repost'
    | 'follow'
    | 'mention'
    | 'reply'
    | 'quote'
    | 'starterpack-joined'
    | 'verified'
    | 'unverified'
    | 'like-via-repost'
    | 'repost-via-repost'
    | 'subscribed-post'
    | 'contact-match'
    | l.UnknownString
  record: l.LexMap
  indexedAt: l.DatetimeString
  reasonSubject?: l.AtUriString
}

export type { Notification }

const notification = l.typedObject<Notification>(
  $nsid,
  'notification',
  l.object({
    cid: l.string({ format: 'cid' }),
    uri: l.string({ format: 'at-uri' }),
    author: l.ref<ActorDefs.ProfileView>((() => ActorDefs.profileView) as any),
    isRead: l.boolean(),
    labels: l.optional(
      l.array(l.ref<LabelDefs.Label>((() => LabelDefs.label) as any)),
    ),
    reason: l.string<{
      knownValues: [
        'like',
        'repost',
        'follow',
        'mention',
        'reply',
        'quote',
        'starterpack-joined',
        'verified',
        'unverified',
        'like-via-repost',
        'repost-via-repost',
        'subscribed-post',
        'contact-match',
      ]
    }>(),
    record: l.lexMap(),
    indexedAt: l.string({ format: 'datetime' }),
    reasonSubject: l.optional(l.string({ format: 'at-uri' })),
  }),
)

export { notification }
