import StyleDictionary from "style-dictionary";

const toCamel = (str) => str.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

// rgba()/hsl() を 8桁hex に変換せず保持
StyleDictionary.registerTransform({
	name: "color/preserve",
	type: "value",
	transitive: true,
	filter: (token) => token.type === "color",
	transform: (token) => token.value,
});
StyleDictionary.registerTransformGroup({
	name: "js-aero",
	transforms: ["attribute/cti", "name/camel", "color/preserve", "size/rem"],
});
StyleDictionary.registerTransformGroup({
	name: "css-aero",
	transforms: ["attribute/cti", "name/kebab", "color/preserve"],
});

// Format 1: Tamagui tokens (プレーンオブジェクト, no @tamagui/core 依存)
StyleDictionary.registerFormat({
	name: "tamagui/tokens",
	format: ({ dictionary }) => {
		const colors = dictionary.allTokens.filter((t) => t.path[0] === "color");
		const spaces = dictionary.allTokens.filter((t) => t.path[0] === "space");
		const radii = dictionary.allTokens.filter((t) => t.path[0] === "radius");
		const colorEntries = colors.map((t) => `    ${toCamel(t.path.slice(2).join("-"))}: '${t.value}',`).join("\n");
		const spaceEntries = spaces.map((t) => `    ${t.path[1]}: ${t.value},`).join("\n");
		const radiusEntries = radii.map((t) => `    ${t.path[1]}: ${t.value},`).join("\n");
		return [
			"// AUTO-GENERATED by Style Dictionary. Do not edit by hand.",
			"// Plain token data (no @tamagui/core dependency).",
			"// Wrap with createTokens() on the consumer side.",
			"",
			"export const tokens = {",
			"  color: {",
			colorEntries,
			"  },",
			"  space: { true: 0,",
			spaceEntries,
			"  },",
			"  size: { true: 0,",
			spaceEntries,
			"  },",
			"  radius: { true: 0,",
			radiusEntries,
			"  },",
			"  zIndex: { true: 0, 0: 0, 1: 1, 2: 2 },",
			"} as const;",
			"",
		].join("\n");
	},
});

// Format 2: Tamagui themes (light / dark)
StyleDictionary.registerFormat({
	name: "tamagui/themes",
	format: ({ dictionary }) => {
		const themeTokens = dictionary.allTokens.filter((t) => t.path[0] === "theme");
		const modes = [...new Set(themeTokens.map((t) => t.path[1]))];
		const renderTheme = (mode) => {
			const entries = themeTokens
				.filter((t) => t.path[1] === mode)
				.map((t) => `    ${toCamel(t.path.slice(2).join("-"))}: '${t.value}',`)
				.join("\n");
			return `  ${mode}: {\n${entries}\n  },`;
		};
		return [
			"// AUTO-GENERATED by Style Dictionary. Do not edit by hand.",
			"export const themes = {",
			modes.map(renderTheme).join("\n"),
			"} as const;",
			"",
		].join("\n");
	},
});

// Format 3: Frutiger Aero 装飾トークン (light/dark 共通)
StyleDictionary.registerFormat({
	name: "tamagui/decoration",
	format: ({ dictionary }) => {
		const glass = dictionary.allTokens.filter((t) => t.path[0] === "glass");
		const input = dictionary.allTokens.filter((t) => t.path[0] === "input");
		const render = (tokens) => tokens.map((t) => `  ${toCamel(t.path.join("-"))}: '${t.value}',`).join("\n");
		return [
			"// AUTO-GENERATED by Style Dictionary. Do not edit by hand.",
			"// Frutiger Aero 装飾色 (light/dark 共通)。",
			"export const aero = {",
			render(glass),
			render(input),
			"} as const;",
			"",
		].join("\n");
	},
});

// Format 4: Tailwind v4 — @theme (base + light semantic) + .dark (dark semantic 上書き)
//   セマンティックキーは Tamagui themes と同じ集合。変数名は light/dark で同一。
StyleDictionary.registerFormat({
	name: "tailwind/v4",
	format: ({ dictionary }) => {
		const colors = dictionary.allTokens.filter((t) => t.path[0] === "color");
		const spaces = dictionary.allTokens.filter((t) => t.path[0] === "space");
		const radii = dictionary.allTokens.filter((t) => t.path[0] === "radius");
		const themeTokens = dictionary.allTokens.filter((t) => t.path[0] === "theme");

		const colorVars = colors.map((t) => `  --color-${t.path.slice(2).join("-")}: ${t.value};`).join("\n");
		const spaceVars = spaces.map((t) => `  --spacing-${t.path[1]}: ${t.value}px;`).join("\n");
		const radiusVars = radii.map((t) => `  --radius-${t.path[1]}: ${t.value}px;`).join("\n");

		// セマンティック変数: --color-<key>。light/dark で同名、値だけ変わる。
		const semanticVars = (mode) =>
			themeTokens
				.filter((t) => t.path[1] === mode)
				.map((t) => `  --color-${t.path.slice(2).join("-")}: ${t.value};`)
				.join("\n");

		return [
			"/* AUTO-GENERATED by Style Dictionary. Do not edit by hand. */",
			"",
			"@theme {",
			colorVars,
			spaceVars,
			radiusVars,
			"",
			"  /* semantic (light) */",
			semanticVars("light"),
			"}",
			"",
			"/* dark: セマンティック変数のみ上書き (変数名は light と同一) */",
			".dark {",
			semanticVars("dark"),
			"}",
			"",
		].join("\n");
	},
});

export default {
	source: ["tokens/**/*.json"],
	platforms: {
		tamaguiTokens: {
			transformGroup: "js-aero",
			buildPath: "build/",
			files: [{ destination: "tokens.ts", format: "tamagui/tokens" }],
		},
		tamaguiThemes: {
			transformGroup: "js-aero",
			buildPath: "build/",
			files: [{ destination: "themes.ts", format: "tamagui/themes" }],
		},
		tamaguiDecoration: {
			transformGroup: "js-aero",
			buildPath: "build/",
			files: [{ destination: "aero.ts", format: "tamagui/decoration" }],
		},
		tailwind: {
			transformGroup: "css-aero",
			buildPath: "build/",
			files: [{ destination: "tailwind.css", format: "tailwind/v4" }],
		},
	},
};
