/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atproto.repo.getRecord'

export { $nsid }

/** Get a single record from a repository. Does not require auth. */
const main = l.query(
  $nsid,
  l.params({
    cid: l.optional(l.string({ format: 'cid' })),
    collection: l.string({ format: 'nsid' }),
    repo: l.string({ format: 'at-identifier' }),
    rkey: l.string({ format: 'record-key' }),
  }),
  l.jsonPayload({
    cid: l.optional(l.string({ format: 'cid' })),
    uri: l.string({ format: 'at-uri' }),
    value: l.lexMap(),
  }),
  ['RecordNotFound'],
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
